### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by dkirker** [filmor/webos-messaging#14]
Not entirely sure what to do with this, but I figure that here might work, so that it is somewhere in case someone else has this problem...

I believe that this is because of an issue with waf trying to look for gcc. Any recommendations?

Commands and output:

```
dkirker@Flying-Toaster:~/projects/webOS/webos-messaging $ export CHOST=arm-none-linux-gnueabi
dkirker@Flying-Toaster:~/projects/webOS/webos-messaging $ echo $CHOST
arm-none-linux-gnueabi
dkirker@Flying-Toaster:~/projects/webOS/webos-messaging $ 
dkirker@Flying-Toaster:~/projects/webOS/webos-messaging $ ./waf configure -v
Setting top to                           : /Users/dkirker/projects/webOS/webos-messaging 
Setting out to                           : /Users/dkirker/projects/webOS/webos-messaging/build 
/media/cryptofs/apps/usr/palm/applications/org.webosinternals.purple
Checking for 'gcc' (c compiler)          : /usr/bin/gcc 
Checking for program msgfmt              : /opt/local/bin/msgfmt 
Checking for program perl                : /opt/local/bin/perl 
Checking for 'intltool-merge'            : /opt/local/bin/intltool-merge 
Checking for header locale.h             : 15:10:19 runner ['/usr/bin/gcc', '-arch', '-march=armv7-a', '-g3', '-Wall', '-DLOCALEDIR="/usr/local/share/locale"', '-DDATADIR="/usr/local/share"', '../test.c', '-c', '-o', 'test.c.1.o']
not found 
The configuration failed
(complete log in /Users/dkirker/projects/webOS/webos-messaging/build/config.log)

dkirker@Flying-Toaster:~/projects/webOS/webos-messaging $ cat /Users/dkirker/projects/webOS/webos-messaging/build/config.log
# project org.webosinternals.purple (0.9.4) configured on Mon Sep 24 15:10:19 2012 by
# waf 1.6.7 (abi 98, python 20601f0 on darwin)
# using ./waf configure -v
#
----------------------------------------
Setting top to
/Users/dkirker/projects/webOS/webos-messaging
----------------------------------------
Setting out to
/Users/dkirker/projects/webOS/webos-messaging/build
----------------------------------------
Checking for 'gcc' (c compiler)
find program=['gcc', 'cc'] paths=['/opt/local/bin', '/opt/local/sbin', '/opt/sshfs/bin/', '/opt/subversion/bin/', '/opt/local/bin', '/opt/local/sbin', '/sw/bin', '/sw/sbin', '/Users/dkirker/Desktop/Development/Android/android-ndk-r4b/build/prebuilt/darwin-x86/arm-eabi-4.2.1/bin', '/bin', '/sbin', '/usr/bin', '/usr/local/bin', '/usr/sbin', '/usr/local/bin', '/Users/dkirker/bin', '/usr/local/git/bin', '/opt/PalmSDK/Current/bin/', '/opt/PalmPDK/arm-gcc/bin/', '/opt/PalmPDK/bin/', '/usr/X11R6/bin'] var='CC' -> '/usr/bin/gcc'
find program=['ar'] paths=['/opt/local/bin', '/opt/local/sbin', '/opt/sshfs/bin/', '/opt/subversion/bin/', '/opt/local/bin', '/opt/local/sbin', '/sw/bin', '/sw/sbin', '/Users/dkirker/Desktop/Development/Android/android-ndk-r4b/build/prebuilt/darwin-x86/arm-eabi-4.2.1/bin', '/bin', '/sbin', '/usr/bin', '/usr/local/bin', '/usr/sbin', '/usr/local/bin', '/Users/dkirker/bin', '/usr/local/git/bin', '/opt/PalmSDK/Current/bin/', '/opt/PalmPDK/arm-gcc/bin/', '/opt/PalmPDK/bin/', '/usr/X11R6/bin'] var='AR' -> '/usr/bin/ar'
/usr/bin/gcc
----------------------------------------
Checking for program msgfmt
/opt/local/bin/msgfmt
find program=['msgfmt'] paths=['/opt/local/bin', '/opt/local/sbin', '/opt/sshfs/bin/', '/opt/subversion/bin/', '/opt/local/bin', '/opt/local/sbin', '/sw/bin', '/sw/sbin', '/Users/dkirker/Desktop/Development/Android/android-ndk-r4b/build/prebuilt/darwin-x86/arm-eabi-4.2.1/bin', '/bin', '/sbin', '/usr/bin', '/usr/local/bin', '/usr/sbin', '/usr/local/bin', '/Users/dkirker/bin', '/usr/local/git/bin', '/opt/PalmSDK/Current/bin/', '/opt/PalmPDK/arm-gcc/bin/', '/opt/PalmPDK/bin/', '/usr/X11R6/bin'] var='MSGFMT' -> '/opt/local/bin/msgfmt'
----------------------------------------
Checking for program perl
/opt/local/bin/perl
find program=['perl'] paths=['/opt/local/bin', '/opt/local/sbin', '/opt/sshfs/bin/', '/opt/subversion/bin/', '/opt/local/bin', '/opt/local/sbin', '/sw/bin', '/sw/sbin', '/Users/dkirker/Desktop/Development/Android/android-ndk-r4b/build/prebuilt/darwin-x86/arm-eabi-4.2.1/bin', '/bin', '/sbin', '/usr/bin', '/usr/local/bin', '/usr/sbin', '/usr/local/bin', '/Users/dkirker/bin', '/usr/local/git/bin', '/opt/PalmSDK/Current/bin/', '/opt/PalmPDK/arm-gcc/bin/', '/opt/PalmPDK/bin/', '/usr/X11R6/bin'] var='PERL' -> '/opt/local/bin/perl'
----------------------------------------
Checking for 'intltool-merge'
/opt/local/bin/intltool-merge
----------------------------------------
Checking for header locale.h
==>
#include <locale.h>

int main() {
    return 0;
}

<==
[1/2] c: build/.conf_check_1d8a90333804c625ba9f36be397a4597/test.c -> build/.conf_check_1d8a90333804c625ba9f36be397a4597/testbuild/test.c.1.o

['/usr/bin/gcc', '-arch', '-march=armv7-a', '-g3', '-Wall', '-DLOCALEDIR="/usr/local/share/locale"', '-DDATADIR="/usr/local/share"', '../test.c', '-c', '-o', 'test.c.1.o']
err: gcc-4.2: Invalid arch name : -march=armv7-a

from /Users/dkirker/projects/webOS/webos-messaging: Test does not build: Traceback (most recent call last):
  File "/Users/dkirker/projects/webOS/webos-messaging/.waf-1.6.7-2743997ca720bb7c095a2cf724370e61/waflib/Tools/c_config.py", line 435, in run_c_code
    bld.compile()
  File "/Users/dkirker/projects/webOS/webos-messaging/.waf-1.6.7-2743997ca720bb7c095a2cf724370e61/waflib/Tools/errcheck.py", line 116, in check_compile
    ret=self.orig_compile()
  File "/Users/dkirker/projects/webOS/webos-messaging/.waf-1.6.7-2743997ca720bb7c095a2cf724370e61/waflib/Build.py", line 193, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task failed (exit status 1): 
    {task 4303064976: c test.c -> test.c.1.o}
['/usr/bin/gcc', '-arch', '-march=armv7-a', '-g3', '-Wall', '-DLOCALEDIR="/usr/local/share/locale"', '-DDATADIR="/usr/local/share"', '../test.c', '-c', '-o', 'test.c.1.o']

not found
from /Users/dkirker/projects/webOS/webos-messaging: The configuration failed
```

**Comment by filmor** [comment]
You either need to move the PalmPDK arm-gcc forward in your $PATH variable or explicitly set `CC=arm-none-linux-gnueabi-gcc` and `CXX=arm-none-linux-gnueabi-g++`. Does that fix things?

**Comment by dkirker** [comment]
Yes! That did. I have NO idea why I hadn't thought of that when I was trying to set environment variables. Thank you! I will note that in the readme when I create a pull request for some fixes that I am working on (I'll probably just write a script to do that, as well).
